#!/usr/bin/env bash

set -e

if [[ "$(command -v apt-get)" != "" ]]; then
	sudo apt-get install libtime-hires-perl -y
fi

(
cd ~/env/dot
for FILE in *; do
	cp $FILE ~/.$FILE
done
)

if [[ ! -d ~/bin ]]; then
	mkdir ~/bin
fi
cp ~/env/bin/* ~/bin

~/env/git-config

if [[ ! -f ~/.bashrc ]]; then
	touch ~/.bashrc
fi
grep -q "source $HOME/env/bashrc" ~/.bashrc || echo "source $HOME/env/bashrc" >> ~/.bashrc
source ~/.bashrc

if [[ ! -f ~/.bash_profile ]]; then
	echo ". ~/.bashrc" > ~/.bash_profile
fi
