#!/usr/bin/env bash

set -e

case $OSTYPE in
(darwin*)
	;;
(linux*)
	DIST=$(lsb_release -si)
	case ${DIST} in
	(Ubuntu)
		sudo apt-get update
		sudo apt-get install -y \
			libtime-hires-perl \
			vim
		;;
	esac
esac

(
cd ~/env/dot
for FILE in *; do
	cp $FILE ~/.$FILE
done
)

mkdir -p ~/bin ~/sw
cp ~/env/bin/* ~/bin

~/env/git-config

if [[ ! -f ~/.bashrc ]]; then
	touch ~/.bashrc
fi
grep -q "source $HOME/env/bashrc" ~/.bashrc || echo "source $HOME/env/bashrc" >> ~/.bashrc
source ~/.bashrc

if [[ ! -f ~/.bash_profile ]]; then
	echo ". ~/.bashrc" > ~/.bash_profile
fi
